#!/bin/bash

if [[ $# -eq 1 ]]; then
	opt -print-callgraph "$1" 1> /dev/null 2> ./callgraph.txt
	./main ./callgraph.txt
		
elif [[ $# -eq 3 ]]; then
	opt -print-callgraph "$1" 1> /dev/null 2> ./callgraph.txt
	./main ./callgraph.txt "$2" "$3"
else
	echo "invalid arguments"
fi
	
